//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Frost.Client.Shared.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Nationalities {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Nationalities() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Frost.Client.Shared.Resources.Nationalities", typeof(Nationalities).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afgańska.
        /// </summary>
        public static string Afghan {
            get {
                return ResourceManager.GetString("Afghan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Albańska.
        /// </summary>
        public static string Albanian {
            get {
                return ResourceManager.GetString("Albanian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Algierska.
        /// </summary>
        public static string Algerian {
            get {
                return ResourceManager.GetString("Algerian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amerykańska.
        /// </summary>
        public static string American {
            get {
                return ResourceManager.GetString("American", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Androska.
        /// </summary>
        public static string Andorran {
            get {
                return ResourceManager.GetString("Andorran", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angolska.
        /// </summary>
        public static string Angolan {
            get {
                return ResourceManager.GetString("Angolan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antiguan.
        /// </summary>
        public static string Antiguans {
            get {
                return ResourceManager.GetString("Antiguans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argentyńska.
        /// </summary>
        public static string Argentinean {
            get {
                return ResourceManager.GetString("Argentinean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Armeńska.
        /// </summary>
        public static string Armenian {
            get {
                return ResourceManager.GetString("Armenian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Australijska.
        /// </summary>
        public static string Australian {
            get {
                return ResourceManager.GetString("Australian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Austriacka.
        /// </summary>
        public static string Austrian {
            get {
                return ResourceManager.GetString("Austrian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azerbejdżańska.
        /// </summary>
        public static string Azerbaijani {
            get {
                return ResourceManager.GetString("Azerbaijani", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bahamska.
        /// </summary>
        public static string Bahamian {
            get {
                return ResourceManager.GetString("Bahamian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bahrajska.
        /// </summary>
        public static string Bahraini {
            get {
                return ResourceManager.GetString("Bahraini", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bangladeska.
        /// </summary>
        public static string Bangladeshi {
            get {
                return ResourceManager.GetString("Bangladeshi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barbadoska.
        /// </summary>
        public static string Barbadian {
            get {
                return ResourceManager.GetString("Barbadian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barbudzka.
        /// </summary>
        public static string Barbudans {
            get {
                return ResourceManager.GetString("Barbudans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Botswańska.
        /// </summary>
        public static string Batswana {
            get {
                return ResourceManager.GetString("Batswana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Białoruska.
        /// </summary>
        public static string Belarusian {
            get {
                return ResourceManager.GetString("Belarusian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Belgijska.
        /// </summary>
        public static string Belgian {
            get {
                return ResourceManager.GetString("Belgian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Belizeńska.
        /// </summary>
        public static string Belizean {
            get {
                return ResourceManager.GetString("Belizean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benińska.
        /// </summary>
        public static string Beninese {
            get {
                return ResourceManager.GetString("Beninese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bhutańska.
        /// </summary>
        public static string Bhutanese {
            get {
                return ResourceManager.GetString("Bhutanese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boliwijska.
        /// </summary>
        public static string Bolivian {
            get {
                return ResourceManager.GetString("Bolivian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bośniacka.
        /// </summary>
        public static string Bosnian {
            get {
                return ResourceManager.GetString("Bosnian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brazylijska.
        /// </summary>
        public static string Brazilian {
            get {
                return ResourceManager.GetString("Brazilian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brytyjska.
        /// </summary>
        public static string British {
            get {
                return ResourceManager.GetString("British", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brunejska.
        /// </summary>
        public static string Bruneian {
            get {
                return ResourceManager.GetString("Bruneian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bułgarska.
        /// </summary>
        public static string Bulgarian {
            get {
                return ResourceManager.GetString("Bulgarian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Burkina Faso.
        /// </summary>
        public static string Burkinabe {
            get {
                return ResourceManager.GetString("Burkinabe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Burmska.
        /// </summary>
        public static string Burmese {
            get {
                return ResourceManager.GetString("Burmese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Burundyjska.
        /// </summary>
        public static string Burundian {
            get {
                return ResourceManager.GetString("Burundian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kambodżańska.
        /// </summary>
        public static string Cambodian {
            get {
                return ResourceManager.GetString("Cambodian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kameruńska.
        /// </summary>
        public static string Cameroonian {
            get {
                return ResourceManager.GetString("Cameroonian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kanadyjska.
        /// </summary>
        public static string Canadian {
            get {
                return ResourceManager.GetString("Canadian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyspy Zielonego Przylądka.
        /// </summary>
        public static string Cape_Verdean {
            get {
                return ResourceManager.GetString("Cape_Verdean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Srodkowoafrykańska.
        /// </summary>
        public static string Central_African {
            get {
                return ResourceManager.GetString("Central_African", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czadyjska.
        /// </summary>
        public static string Chadian {
            get {
                return ResourceManager.GetString("Chadian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chilijska.
        /// </summary>
        public static string Chilean {
            get {
                return ResourceManager.GetString("Chilean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chińska.
        /// </summary>
        public static string Chinese {
            get {
                return ResourceManager.GetString("Chinese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kolumbijska.
        /// </summary>
        public static string Colombian {
            get {
                return ResourceManager.GetString("Colombian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Komoryjska.
        /// </summary>
        public static string Comoran {
            get {
                return ResourceManager.GetString("Comoran", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kongijska.
        /// </summary>
        public static string Congolese {
            get {
                return ResourceManager.GetString("Congolese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kostarykańska.
        /// </summary>
        public static string Costa_Rican {
            get {
                return ResourceManager.GetString("Costa_Rican", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chorwacka.
        /// </summary>
        public static string Croatian {
            get {
                return ResourceManager.GetString("Croatian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kubańska.
        /// </summary>
        public static string Cuban {
            get {
                return ResourceManager.GetString("Cuban", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cypryjska.
        /// </summary>
        public static string Cypriot {
            get {
                return ResourceManager.GetString("Cypriot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czeska.
        /// </summary>
        public static string Czech {
            get {
                return ResourceManager.GetString("Czech", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duńska.
        /// </summary>
        public static string Danish {
            get {
                return ResourceManager.GetString("Danish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dżibucka.
        /// </summary>
        public static string Djibouti {
            get {
                return ResourceManager.GetString("Djibouti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dominikańska.
        /// </summary>
        public static string Dominican {
            get {
                return ResourceManager.GetString("Dominican", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Holenderska.
        /// </summary>
        public static string Dutch {
            get {
                return ResourceManager.GetString("Dutch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timor Wschodni.
        /// </summary>
        public static string East_Timorese {
            get {
                return ResourceManager.GetString("East_Timorese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ekwadorska.
        /// </summary>
        public static string Ecuadorean {
            get {
                return ResourceManager.GetString("Ecuadorean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Egipska.
        /// </summary>
        public static string Egyptian {
            get {
                return ResourceManager.GetString("Egyptian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emiraty Arabskie.
        /// </summary>
        public static string Emirian {
            get {
                return ResourceManager.GetString("Emirian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gwinea Równikowa.
        /// </summary>
        public static string Equatorial_Guinean {
            get {
                return ResourceManager.GetString("Equatorial_Guinean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erytreańska.
        /// </summary>
        public static string Eritrean {
            get {
                return ResourceManager.GetString("Eritrean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estońska.
        /// </summary>
        public static string Estonian {
            get {
                return ResourceManager.GetString("Estonian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etiopska.
        /// </summary>
        public static string Ethiopian {
            get {
                return ResourceManager.GetString("Ethiopian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fidżyjska.
        /// </summary>
        public static string Fijian {
            get {
                return ResourceManager.GetString("Fijian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filipińska.
        /// </summary>
        public static string Filipino {
            get {
                return ResourceManager.GetString("Filipino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fińska.
        /// </summary>
        public static string Finnish {
            get {
                return ResourceManager.GetString("Finnish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Francuska.
        /// </summary>
        public static string French {
            get {
                return ResourceManager.GetString("French", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gabońska.
        /// </summary>
        public static string Gabonese {
            get {
                return ResourceManager.GetString("Gabonese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gambijska.
        /// </summary>
        public static string Gambian {
            get {
                return ResourceManager.GetString("Gambian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gruzińska.
        /// </summary>
        public static string Georgian {
            get {
                return ResourceManager.GetString("Georgian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niemiecka.
        /// </summary>
        public static string German {
            get {
                return ResourceManager.GetString("German", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ghańska.
        /// </summary>
        public static string Ghanaian {
            get {
                return ResourceManager.GetString("Ghanaian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grecka.
        /// </summary>
        public static string Greek {
            get {
                return ResourceManager.GetString("Greek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grenadzka.
        /// </summary>
        public static string Grenadian {
            get {
                return ResourceManager.GetString("Grenadian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gwatemalska.
        /// </summary>
        public static string Guatemalan {
            get {
                return ResourceManager.GetString("Guatemalan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gwinea Bissau.
        /// </summary>
        public static string GuineaBissauan {
            get {
                return ResourceManager.GetString("GuineaBissauan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gwinejska.
        /// </summary>
        public static string Guinean {
            get {
                return ResourceManager.GetString("Guinean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gujańska.
        /// </summary>
        public static string Guyanese {
            get {
                return ResourceManager.GetString("Guyanese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haitańska.
        /// </summary>
        public static string Haitian {
            get {
                return ResourceManager.GetString("Haitian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bośnia i Hercegowina.
        /// </summary>
        public static string Herzegovinian {
            get {
                return ResourceManager.GetString("Herzegovinian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Honduraska.
        /// </summary>
        public static string Honduran {
            get {
                return ResourceManager.GetString("Honduran", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Węgierska.
        /// </summary>
        public static string Hungarian {
            get {
                return ResourceManager.GetString("Hungarian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Islandzka.
        /// </summary>
        public static string Icelander {
            get {
                return ResourceManager.GetString("Icelander", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indyjska.
        /// </summary>
        public static string Indian {
            get {
                return ResourceManager.GetString("Indian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indonezyjska.
        /// </summary>
        public static string Indonesian {
            get {
                return ResourceManager.GetString("Indonesian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Irańska.
        /// </summary>
        public static string Iranian {
            get {
                return ResourceManager.GetString("Iranian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Irakijska.
        /// </summary>
        public static string Iraqi {
            get {
                return ResourceManager.GetString("Iraqi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Irlandzka.
        /// </summary>
        public static string Irish {
            get {
                return ResourceManager.GetString("Irish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izraelicka.
        /// </summary>
        public static string Israeli {
            get {
                return ResourceManager.GetString("Israeli", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Włoska.
        /// </summary>
        public static string Italian {
            get {
                return ResourceManager.GetString("Italian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wybrzeże Kości Słoniowej.
        /// </summary>
        public static string Ivorian {
            get {
                return ResourceManager.GetString("Ivorian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jamajska.
        /// </summary>
        public static string Jamaican {
            get {
                return ResourceManager.GetString("Jamaican", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Japońska.
        /// </summary>
        public static string Japanese {
            get {
                return ResourceManager.GetString("Japanese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jordańska.
        /// </summary>
        public static string Jordanian {
            get {
                return ResourceManager.GetString("Jordanian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kazachstańska.
        /// </summary>
        public static string Kazakhstani {
            get {
                return ResourceManager.GetString("Kazakhstani", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kenijska.
        /// </summary>
        public static string Kenyan {
            get {
                return ResourceManager.GetString("Kenyan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kiribatyjska.
        /// </summary>
        public static string Kiribati {
            get {
                return ResourceManager.GetString("Kiribati", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saint Kitts i Nevis.
        /// </summary>
        public static string Kittian_and_Nevisian {
            get {
                return ResourceManager.GetString("Kittian_and_Nevisian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kuwejcka.
        /// </summary>
        public static string Kuwaiti {
            get {
                return ResourceManager.GetString("Kuwaiti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kirgiska.
        /// </summary>
        public static string Kyrgyz {
            get {
                return ResourceManager.GetString("Kyrgyz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laotańska.
        /// </summary>
        public static string Laotian {
            get {
                return ResourceManager.GetString("Laotian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Łotewska.
        /// </summary>
        public static string Latvian {
            get {
                return ResourceManager.GetString("Latvian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Libańska.
        /// </summary>
        public static string Lebanese {
            get {
                return ResourceManager.GetString("Lebanese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liberyjska.
        /// </summary>
        public static string Liberian {
            get {
                return ResourceManager.GetString("Liberian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Libijska.
        /// </summary>
        public static string Libyan {
            get {
                return ResourceManager.GetString("Libyan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lichtenstein.
        /// </summary>
        public static string Liechtensteiner {
            get {
                return ResourceManager.GetString("Liechtensteiner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Litewska.
        /// </summary>
        public static string Lithuanian {
            get {
                return ResourceManager.GetString("Lithuanian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Luksemurska.
        /// </summary>
        public static string Luxembourger {
            get {
                return ResourceManager.GetString("Luxembourger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Macedońska.
        /// </summary>
        public static string Macedonian {
            get {
                return ResourceManager.GetString("Macedonian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Madagaskarska.
        /// </summary>
        public static string Malagasy {
            get {
                return ResourceManager.GetString("Malagasy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Malawijska.
        /// </summary>
        public static string Malawian {
            get {
                return ResourceManager.GetString("Malawian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Malezyjska.
        /// </summary>
        public static string Malaysian {
            get {
                return ResourceManager.GetString("Malaysian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Malediwska.
        /// </summary>
        public static string Maldivian {
            get {
                return ResourceManager.GetString("Maldivian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Malijska.
        /// </summary>
        public static string Malian {
            get {
                return ResourceManager.GetString("Malian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maltańska.
        /// </summary>
        public static string Maltese {
            get {
                return ResourceManager.GetString("Maltese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyspy Marshalla.
        /// </summary>
        public static string Marshallese {
            get {
                return ResourceManager.GetString("Marshallese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mauretańska.
        /// </summary>
        public static string Mauritanian {
            get {
                return ResourceManager.GetString("Mauritanian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maurytyjska.
        /// </summary>
        public static string Mauritian {
            get {
                return ResourceManager.GetString("Mauritian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meksykańska.
        /// </summary>
        public static string Mexican {
            get {
                return ResourceManager.GetString("Mexican", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mikronezyjska.
        /// </summary>
        public static string Micronesian {
            get {
                return ResourceManager.GetString("Micronesian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mołdawska.
        /// </summary>
        public static string Moldovan {
            get {
                return ResourceManager.GetString("Moldovan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monakijska.
        /// </summary>
        public static string Monacan {
            get {
                return ResourceManager.GetString("Monacan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mongolska.
        /// </summary>
        public static string Mongolian {
            get {
                return ResourceManager.GetString("Mongolian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marokańska.
        /// </summary>
        public static string Moroccan {
            get {
                return ResourceManager.GetString("Moroccan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mosotho.
        /// </summary>
        public static string Mosotho {
            get {
                return ResourceManager.GetString("Mosotho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Botswańska.
        /// </summary>
        public static string Motswana {
            get {
                return ResourceManager.GetString("Motswana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mozambijska.
        /// </summary>
        public static string Mozambican {
            get {
                return ResourceManager.GetString("Mozambican", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nambijska.
        /// </summary>
        public static string Namibian {
            get {
                return ResourceManager.GetString("Namibian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nauruańska.
        /// </summary>
        public static string Nauruan {
            get {
                return ResourceManager.GetString("Nauruan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nepalska.
        /// </summary>
        public static string Nepalese {
            get {
                return ResourceManager.GetString("Nepalese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nowozelandzka.
        /// </summary>
        public static string New_Zealander {
            get {
                return ResourceManager.GetString("New_Zealander", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nikaraguańska.
        /// </summary>
        public static string Nicaraguan {
            get {
                return ResourceManager.GetString("Nicaraguan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nigeryjska.
        /// </summary>
        public static string Nigerian {
            get {
                return ResourceManager.GetString("Nigerian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nigerska.
        /// </summary>
        public static string Nigerien {
            get {
                return ResourceManager.GetString("Nigerien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brak.
        /// </summary>
        public static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korea Północna.
        /// </summary>
        public static string North_Korean {
            get {
                return ResourceManager.GetString("North_Korean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Irlandia Północna.
        /// </summary>
        public static string Northern_Irish {
            get {
                return ResourceManager.GetString("Northern_Irish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Norweska.
        /// </summary>
        public static string Norwegian {
            get {
                return ResourceManager.GetString("Norwegian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Omańska.
        /// </summary>
        public static string Omani {
            get {
                return ResourceManager.GetString("Omani", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pakistańska.
        /// </summary>
        public static string Pakistani {
            get {
                return ResourceManager.GetString("Pakistani", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Palau.
        /// </summary>
        public static string Palauan {
            get {
                return ResourceManager.GetString("Palauan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Panamska.
        /// </summary>
        public static string Panamanian {
            get {
                return ResourceManager.GetString("Panamanian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Papua-Nowa Gwinea.
        /// </summary>
        public static string Papua_New_Guinean {
            get {
                return ResourceManager.GetString("Papua_New_Guinean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paragwajska.
        /// </summary>
        public static string Paraguayan {
            get {
                return ResourceManager.GetString("Paraguayan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peruwiańska.
        /// </summary>
        public static string Peruvian {
            get {
                return ResourceManager.GetString("Peruvian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polska.
        /// </summary>
        public static string Polish {
            get {
                return ResourceManager.GetString("Polish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portugalska.
        /// </summary>
        public static string Portuguese {
            get {
                return ResourceManager.GetString("Portuguese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Katarska.
        /// </summary>
        public static string Qatari {
            get {
                return ResourceManager.GetString("Qatari", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rumuńska.
        /// </summary>
        public static string Romanian {
            get {
                return ResourceManager.GetString("Romanian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rosyjska.
        /// </summary>
        public static string Russian {
            get {
                return ResourceManager.GetString("Russian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rwandyjska.
        /// </summary>
        public static string Rwandan {
            get {
                return ResourceManager.GetString("Rwandan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saint Lucia.
        /// </summary>
        public static string Saint_Lucian {
            get {
                return ResourceManager.GetString("Saint_Lucian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salwadorska.
        /// </summary>
        public static string Salvadoran {
            get {
                return ResourceManager.GetString("Salvadoran", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Samoańska.
        /// </summary>
        public static string Samoan {
            get {
                return ResourceManager.GetString("Samoan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to San Marino.
        /// </summary>
        public static string San_Marinese {
            get {
                return ResourceManager.GetString("San_Marinese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sao Tomean.
        /// </summary>
        public static string Sao_Tomean {
            get {
                return ResourceManager.GetString("Sao_Tomean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabia Saudyjska.
        /// </summary>
        public static string Saudi {
            get {
                return ResourceManager.GetString("Saudi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szkocka.
        /// </summary>
        public static string Scottish {
            get {
                return ResourceManager.GetString("Scottish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senegalska.
        /// </summary>
        public static string Senegalese {
            get {
                return ResourceManager.GetString("Senegalese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serbska.
        /// </summary>
        public static string Serbian {
            get {
                return ResourceManager.GetString("Serbian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seszelska.
        /// </summary>
        public static string Seychellois {
            get {
                return ResourceManager.GetString("Seychellois", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sierra Leone.
        /// </summary>
        public static string Sierra_Leonean {
            get {
                return ResourceManager.GetString("Sierra_Leonean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Singapurska.
        /// </summary>
        public static string Singaporean {
            get {
                return ResourceManager.GetString("Singaporean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Słowacka.
        /// </summary>
        public static string Slovakian {
            get {
                return ResourceManager.GetString("Slovakian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Słoweńska.
        /// </summary>
        public static string Slovenian {
            get {
                return ResourceManager.GetString("Slovenian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyspy Salomona.
        /// </summary>
        public static string Solomon_Islander {
            get {
                return ResourceManager.GetString("Solomon_Islander", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Somalijska.
        /// </summary>
        public static string Somali {
            get {
                return ResourceManager.GetString("Somali", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Republika Południowej Afryki.
        /// </summary>
        public static string South_African {
            get {
                return ResourceManager.GetString("South_African", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korea Południowa.
        /// </summary>
        public static string South_Korean {
            get {
                return ResourceManager.GetString("South_Korean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiszpańska.
        /// </summary>
        public static string Spanish {
            get {
                return ResourceManager.GetString("Spanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sri Lanka.
        /// </summary>
        public static string Sri_Lankan {
            get {
                return ResourceManager.GetString("Sri_Lankan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sudańska.
        /// </summary>
        public static string Sudanese {
            get {
                return ResourceManager.GetString("Sudanese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surinamska.
        /// </summary>
        public static string Surinamer {
            get {
                return ResourceManager.GetString("Surinamer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eswatyńska.
        /// </summary>
        public static string Swazi {
            get {
                return ResourceManager.GetString("Swazi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szwedzka.
        /// </summary>
        public static string Swedish {
            get {
                return ResourceManager.GetString("Swedish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szwajcarska.
        /// </summary>
        public static string Swiss {
            get {
                return ResourceManager.GetString("Swiss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syryjska.
        /// </summary>
        public static string Syrian {
            get {
                return ResourceManager.GetString("Syrian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tajwańska.
        /// </summary>
        public static string Taiwanese {
            get {
                return ResourceManager.GetString("Taiwanese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tadżykistańska.
        /// </summary>
        public static string Tajik {
            get {
                return ResourceManager.GetString("Tajik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tanzańska.
        /// </summary>
        public static string Tanzanian {
            get {
                return ResourceManager.GetString("Tanzanian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tajska.
        /// </summary>
        public static string Thai {
            get {
                return ResourceManager.GetString("Thai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Togijska.
        /// </summary>
        public static string Togolese {
            get {
                return ResourceManager.GetString("Togolese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tongijska.
        /// </summary>
        public static string Tongan {
            get {
                return ResourceManager.GetString("Tongan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trynidad i Tobago.
        /// </summary>
        public static string Trinidadian_or_Tobagonian {
            get {
                return ResourceManager.GetString("Trinidadian_or_Tobagonian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tunezyjska.
        /// </summary>
        public static string Tunisian {
            get {
                return ResourceManager.GetString("Tunisian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turecka.
        /// </summary>
        public static string Turkish {
            get {
                return ResourceManager.GetString("Turkish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuwalska.
        /// </summary>
        public static string Tuvaluan {
            get {
                return ResourceManager.GetString("Tuvaluan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ugandyjska.
        /// </summary>
        public static string Ugandan {
            get {
                return ResourceManager.GetString("Ugandan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ukraińska.
        /// </summary>
        public static string Ukrainian {
            get {
                return ResourceManager.GetString("Ukrainian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Urugwajska.
        /// </summary>
        public static string Uruguayan {
            get {
                return ResourceManager.GetString("Uruguayan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uzbecka.
        /// </summary>
        public static string Uzbekistani {
            get {
                return ResourceManager.GetString("Uzbekistani", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vanuatu.
        /// </summary>
        public static string Vanuatu {
            get {
                return ResourceManager.GetString("Vanuatu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wenezuelska.
        /// </summary>
        public static string Venezuelan {
            get {
                return ResourceManager.GetString("Venezuelan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wietnamska.
        /// </summary>
        public static string Vietnamese {
            get {
                return ResourceManager.GetString("Vietnamese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Walijska.
        /// </summary>
        public static string Welsh {
            get {
                return ResourceManager.GetString("Welsh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jemeńska.
        /// </summary>
        public static string Yemenite {
            get {
                return ResourceManager.GetString("Yemenite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zambijska.
        /// </summary>
        public static string Zambian {
            get {
                return ResourceManager.GetString("Zambian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zimbabweńska.
        /// </summary>
        public static string Zimbabwean {
            get {
                return ResourceManager.GetString("Zimbabwean", resourceCulture);
            }
        }
    }
}
