//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Frost.Client.Shared.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Frost.Client.Shared.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konto.
        /// </summary>
        public static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj zdjęcie.
        /// </summary>
        public static string AddImage {
            get {
                return ResourceManager.GetString("AddImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj ogłoszenie.
        /// </summary>
        public static string AddOffer {
            get {
                return ResourceManager.GetString("AddOffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj użytkowników do czatu.
        /// </summary>
        public static string AddUsersToChat {
            get {
                return ResourceManager.GetString("AddUsersToChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtry zaawansowane.
        /// </summary>
        public static string AdvancedFilters {
            get {
                return ResourceManager.GetString("AdvancedFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ogłoszeniodawca.
        /// </summary>
        public static string Advertiser {
            get {
                return ResourceManager.GetString("Advertiser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zezwól na współlokatorów.
        /// </summary>
        public static string AllowRoommates {
            get {
                return ResourceManager.GetString("AllowRoommates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dowolnie.
        /// </summary>
        public static string Any {
            get {
                return ResourceManager.GetString("Any", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dowolna.
        /// </summary>
        public static string AnyF {
            get {
                return ResourceManager.GetString("AnyF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dowolne.
        /// </summary>
        public static string AnyI {
            get {
                return ResourceManager.GetString("AnyI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dowolny.
        /// </summary>
        public static string AnyM {
            get {
                return ResourceManager.GetString("AnyM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czy na pewno chcesz usunąć konto?.
        /// </summary>
        public static string AreYouSureDeleteAcc {
            get {
                return ResourceManager.GetString("AreYouSureDeleteAcc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zablokuj komunikację.
        /// </summary>
        public static string BlockCommunication {
            get {
                return ResourceManager.GetString("BlockCommunication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rodzaj zabudowy.
        /// </summary>
        public static string BuildingType {
            get {
                return ResourceManager.GetString("BuildingType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprzedaż.
        /// </summary>
        public static string Buy {
            get {
                return ResourceManager.GetString("Buy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anuluj.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anuluj zastępowanie zdjęć.
        /// </summary>
        public static string CancelReplacingPhotos {
            get {
                return ResourceManager.GetString("CancelReplacingPhotos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zmień miasto.
        /// </summary>
        public static string ChangeCity {
            get {
                return ResourceManager.GetString("ChangeCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zmień opis.
        /// </summary>
        public static string ChangeDescription {
            get {
                return ResourceManager.GetString("ChangeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zmień email.
        /// </summary>
        public static string ChangeEmail {
            get {
                return ResourceManager.GetString("ChangeEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zmień imię.
        /// </summary>
        public static string ChangeName {
            get {
                return ResourceManager.GetString("ChangeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zmień narodowość.
        /// </summary>
        public static string ChangeNationality {
            get {
                return ResourceManager.GetString("ChangeNationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zmień hasło.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zmień numer.
        /// </summary>
        public static string ChangeTelNumber {
            get {
                return ResourceManager.GetString("ChangeTelNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miasto.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kliknij aby zastąpić istniejące zdjęcia.
        /// </summary>
        public static string ClickToReplacePhotos {
            get {
                return ResourceManager.GetString("ClickToReplacePhotos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Komunikacja jest zablokowana..
        /// </summary>
        public static string CommunicationIsBlocked {
            get {
                return ResourceManager.GetString("CommunicationIsBlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Na pewno chcesz usunąć ofertę?.
        /// </summary>
        public static string ConfirmDelete {
            get {
                return ResourceManager.GetString("ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potwierdź nowe hasło.
        /// </summary>
        public static string ConfirmNewPassword {
            get {
                return ResourceManager.GetString("ConfirmNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Powtórz hasło.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Powtórz hasło.
        /// </summary>
        public static string ConfirmPasswordPlaceholder {
            get {
                return ResourceManager.GetString("ConfirmPasswordPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typ zabudowy.
        /// </summary>
        public static string ConstructionType {
            get {
                return ResourceManager.GetString("ConstructionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rok budowy.
        /// </summary>
        public static string ConstructionYear {
            get {
                return ResourceManager.GetString("ConstructionYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skopiowano do schowka.
        /// </summary>
        public static string CopiedToClipboard {
            get {
                return ResourceManager.GetString("CopiedToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skopiuj zaproszenie do czatu.
        /// </summary>
        public static string CopyChatInvitation {
            get {
                return ResourceManager.GetString("CopyChatInvitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utworzone.
        /// </summary>
        public static string Created {
            get {
                return ResourceManager.GetString("Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stwórz czat grupowy.
        /// </summary>
        public static string CreateGroupChat {
            get {
                return ResourceManager.GetString("CreateGroupChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data: Najnowsze.
        /// </summary>
        public static string Date_Latest {
            get {
                return ResourceManager.GetString("Date:Latest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data: Najstarsze.
        /// </summary>
        public static string Date_Oldest {
            get {
                return ResourceManager.GetString("Date:Oldest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dni.
        /// </summary>
        public static string Days {
            get {
                return ResourceManager.GetString("Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuń.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuń konto.
        /// </summary>
        public static string DeleteAccount {
            get {
                return ResourceManager.GetString("DeleteAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuń zdjęcie.
        /// </summary>
        public static string DeleteImage {
            get {
                return ResourceManager.GetString("DeleteImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuń ofertę.
        /// </summary>
        public static string DeleteOffer {
            get {
                return ResourceManager.GetString("DeleteOffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuń zapisane filtry.
        /// </summary>
        public static string DeleteSavedFilters {
            get {
                return ResourceManager.GetString("DeleteSavedFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuń konto użytkownika.
        /// </summary>
        public static string DeleteUser {
            get {
                return ResourceManager.GetString("DeleteUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opis.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dzielnica.
        /// </summary>
        public static string District {
            get {
                return ResourceManager.GetString("District", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proszę wybrać dzielnicę z listy.
        /// </summary>
        public static string DistrictNotChosenError {
            get {
                return ResourceManager.GetString("DistrictNotChosenError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Od.
        /// </summary>
        public static string Earliest {
            get {
                return ResourceManager.GetString("Earliest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edytuj.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edytuj ogłoszenie.
        /// </summary>
        public static string EditOffer {
            get {
                return ResourceManager.GetString("EditOffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edytuj szablon.
        /// </summary>
        public static string EditTemplate {
            get {
                return ResourceManager.GetString("EditTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wpisz email.
        /// </summary>
        public static string EmailPlaceholder {
            get {
                return ResourceManager.GetString("EmailPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email jest wymagany.
        /// </summary>
        public static string EmailRequiredError {
            get {
                return ResourceManager.GetString("EmailRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wprowadź aktualne hasło.
        /// </summary>
        public static string EnterCurrentPassword {
            get {
                return ResourceManager.GetString("EnterCurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wprowadź nowe hasło.
        /// </summary>
        public static string EnterNewPassword {
            get {
                return ResourceManager.GetString("EnterNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lokal.
        /// </summary>
        public static string Establishment {
            get {
                return ResourceManager.GetString("Establishment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lokale usługowe.
        /// </summary>
        public static string Establishments {
            get {
                return ResourceManager.GetString("Establishments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bez.
        /// </summary>
        public static string Excluded {
            get {
                return ResourceManager.GetString("Excluded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mieszkanie.
        /// </summary>
        public static string Flat {
            get {
                return ResourceManager.GetString("Flat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mieszkania.
        /// </summary>
        public static string Flats {
            get {
                return ResourceManager.GetString("Flats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Piętro.
        /// </summary>
        public static string Floor {
            get {
                return ResourceManager.GetString("Floor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obserwowane.
        /// </summary>
        public static string Followed {
            get {
                return ResourceManager.GetString("Followed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obserwowane oferty.
        /// </summary>
        public static string FollowedOffers {
            get {
                return ResourceManager.GetString("FollowedOffers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obserwuj ofertę.
        /// </summary>
        public static string FollowOffer {
            get {
                return ResourceManager.GetString("FollowOffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Garaż.
        /// </summary>
        public static string Garage {
            get {
                return ResourceManager.GetString("Garage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Garaże.
        /// </summary>
        public static string Garages {
            get {
                return ResourceManager.GetString("Garages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czat grupowy.
        /// </summary>
        public static string GroupChat {
            get {
                return ResourceManager.GetString("GroupChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apartamentowiec.
        /// </summary>
        public static string HighRise {
            get {
                return ResourceManager.GetString("HighRise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dom.
        /// </summary>
        public static string House {
            get {
                return ResourceManager.GetString("House", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domy.
        /// </summary>
        public static string Houses {
            get {
                return ResourceManager.GetString("Houses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zdjęcie powinno spełniać następujące wymagania:.
        /// </summary>
        public static string ImageRequirements {
            get {
                return ResourceManager.GetString("ImageRequirements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zdjęcia.
        /// </summary>
        public static string Images {
            get {
                return ResourceManager.GetString("Images", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Należy dodać minimum 6 zdjęć ale nie więcej niż 15..
        /// </summary>
        public static string ImagesAmountRequirement {
            get {
                return ResourceManager.GetString("ImagesAmountRequirement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zdjęcia mogą być przesłane w następujących formatach: JPG, PNG, JPEG lub WEBP..
        /// </summary>
        public static string ImagesExtensionRequirement {
            get {
                return ResourceManager.GetString("ImagesExtensionRequirement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zdjęcia powinny spełniać następujące wymagania:.
        /// </summary>
        public static string ImagesRequirements {
            get {
                return ResourceManager.GetString("ImagesRequirements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rozmiar jednego zdjęcia nie powinien przekraczać 5MB..
        /// </summary>
        public static string ImagesSizeRequirement {
            get {
                return ResourceManager.GetString("ImagesSizeRequirement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyłącznie.
        /// </summary>
        public static string Included {
            get {
                return ResourceManager.GetString("Included", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niepoprawny email lub hasło.
        /// </summary>
        public static string InvalidCredentials {
            get {
                return ResourceManager.GetString("InvalidCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nieprawidłowe rozszerzenie pliku.
        /// </summary>
        public static string InvalidExtensionError {
            get {
                return ResourceManager.GetString("InvalidExtensionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nieprawidłowe hasło.
        /// </summary>
        public static string InvalidPassword {
            get {
                return ResourceManager.GetString("InvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zaproszenie wygasło.
        /// </summary>
        public static string InvitationHasExpired {
            get {
                return ResourceManager.GetString("InvitationHasExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zaproszenie jest niepoprawne lub zostało już wykorzystane.
        /// </summary>
        public static string InvitationIsNotValid {
            get {
                return ResourceManager.GetString("InvitationIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dołącz jako pierwszy!.
        /// </summary>
        public static string JoinFirst {
            get {
                return ResourceManager.GetString("JoinFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PL.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do.
        /// </summary>
        public static string Latest {
            get {
                return ResourceManager.GetString("Latest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opuść czat grupowy.
        /// </summary>
        public static string LeaveGroupChat {
            get {
                return ResourceManager.GetString("LeaveGroupChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lokalizacja.
        /// </summary>
        public static string Localization {
            get {
                return ResourceManager.GetString("Localization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lokalizacja.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proszę wybrać miasto z listy.
        /// </summary>
        public static string LocationNotChosenError {
            get {
                return ResourceManager.GetString("LocationNotChosenError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logowanie.
        /// </summary>
        public static string Log_in {
            get {
                return ResourceManager.GetString("Log_in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zaloguj się.
        /// </summary>
        public static string LogIn {
            get {
                return ResourceManager.GetString("LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logowanie.
        /// </summary>
        public static string LoginDetails {
            get {
                return ResourceManager.GetString("LoginDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szczegóły logowania.
        /// </summary>
        public static string LoginDetailsUser {
            get {
                return ResourceManager.GetString("LoginDetailsUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyloguj.
        /// </summary>
        public static string LogOut {
            get {
                return ResourceManager.GetString("LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rynek.
        /// </summary>
        public static string Market {
            get {
                return ResourceManager.GetString("Market", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cena maksymalna.
        /// </summary>
        public static string MaxPrice {
            get {
                return ResourceManager.GetString("MaxPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Powierzchnia do.
        /// </summary>
        public static string MaxSurface {
            get {
                return ResourceManager.GetString("MaxSurface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wiadomości.
        /// </summary>
        public static string Messages {
            get {
                return ResourceManager.GetString("Messages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cena za metr.
        /// </summary>
        public static string MeterPrice {
            get {
                return ResourceManager.GetString("MeterPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cena minimalna.
        /// </summary>
        public static string MinPrice {
            get {
                return ResourceManager.GetString("MinPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Powierzchnia od.
        /// </summary>
        public static string MinSurface {
            get {
                return ResourceManager.GetString("MinSurface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imię.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wpisz imię.
        /// </summary>
        public static string NamePlaceholder {
            get {
                return ResourceManager.GetString("NamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Narodowość.
        /// </summary>
        public static string Nationality {
            get {
                return ResourceManager.GetString("Nationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nowy czat grupowy.
        /// </summary>
        public static string NewGroupChat {
            get {
                return ResourceManager.GetString("NewGroupChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nowe ogłoszenie.
        /// </summary>
        public static string NewOffer {
            get {
                return ResourceManager.GetString("NewOffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brak aktywnych chatów.
        /// </summary>
        public static string NoChats {
            get {
                return ResourceManager.GetString("NoChats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brak.
        /// </summary>
        public static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie znaleziono ogłoszenia.
        /// </summary>
        public static string NoOfferFound {
            get {
                return ResourceManager.GetString("NoOfferFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brak ofert do wyświetlenia.
        /// </summary>
        public static string NoOffers {
            get {
                return ResourceManager.GetString("NoOffers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brak wyników.
        /// </summary>
        public static string NoResults {
            get {
                return ResourceManager.GetString("NoResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brak szablonów.
        /// </summary>
        public static string NoTemplates {
            get {
                return ResourceManager.GetString("NoTemplates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Należy przeslać conajmniej.
        /// </summary>
        public static string NotEnoughFilesError {
            get {
                return ResourceManager.GetString("NotEnoughFilesError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to plików.
        /// </summary>
        public static string NotEnoughFilesError_files {
            get {
                return ResourceManager.GetString("NotEnoughFilesError_files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Powiadomienia.
        /// </summary>
        public static string Notifications {
            get {
                return ResourceManager.GetString("Notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chce otrzymywać powiadomienia Email w razie zmiany szczegółów konta.
        /// </summary>
        public static string NotifyAboutChangedLoginDetails {
            get {
                return ResourceManager.GetString("NotifyAboutChangedLoginDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chce otrzymywać powiadomienia Email o moich wygasających ogłoszeniach.
        /// </summary>
        public static string NotifyAboutExpiringOffers {
            get {
                return ResourceManager.GetString("NotifyAboutExpiringOffers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chce otrzymywać powiadomienia Email o nowych wiadomościach.
        /// </summary>
        public static string NotifyAboutNewMessages {
            get {
                return ResourceManager.GetString("NotifyAboutNewMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chce otrzymywać powiadomienia Email o nowych ofertach.
        /// </summary>
        public static string NotifyAboutNewOffers {
            get {
                return ResourceManager.GetString("NotifyAboutNewOffers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szczegóły ogłoszenia.
        /// </summary>
        public static string OfferDetails {
            get {
                return ResourceManager.GetString("OfferDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ogłoszenia.
        /// </summary>
        public static string Offers {
            get {
                return ResourceManager.GetString("Offers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typ oferty.
        /// </summary>
        public static string OfferType {
            get {
                return ResourceManager.GetString("OfferType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hasło.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wpisz hasło.
        /// </summary>
        public static string PasswordPlaceholder {
            get {
                return ResourceManager.GetString("PasswordPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zdjęcie.
        /// </summary>
        public static string Picture {
            get {
                return ResourceManager.GetString("Picture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Działka.
        /// </summary>
        public static string Plot {
            get {
                return ResourceManager.GetString("Plot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Działki.
        /// </summary>
        public static string Plots {
            get {
                return ResourceManager.GetString("Plots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cena.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cena: Największa.
        /// </summary>
        public static string Price_Highest {
            get {
                return ResourceManager.GetString("Price:Highest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cena: Najmniejsza.
        /// </summary>
        public static string Price_Lowest {
            get {
                return ResourceManager.GetString("Price:Lowest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pierwotny.
        /// </summary>
        public static string Primary {
            get {
                return ResourceManager.GetString("Primary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promowane oferty.
        /// </summary>
        public static string PromotedOffers {
            get {
                return ResourceManager.GetString("PromotedOffers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typ nieruchomości.
        /// </summary>
        public static string PropertyType {
            get {
                return ResourceManager.GetString("PropertyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Zarejestruj się.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejestracja.
        /// </summary>
        public static string Registration {
            get {
                return ResourceManager.GetString("Registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wynajem.
        /// </summary>
        public static string Rent {
            get {
                return ResourceManager.GetString("Rent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opublikuj.
        /// </summary>
        public static string Republish {
            get {
                return ResourceManager.GetString("Republish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pole wymagane.
        /// </summary>
        public static string RequiredField {
            get {
                return ResourceManager.GetString("RequiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pokój.
        /// </summary>
        public static string Room {
            get {
                return ResourceManager.GetString("Room", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Współlokatorzy.
        /// </summary>
        public static string Roommates {
            get {
                return ResourceManager.GetString("Roommates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szukają współlokatora.
        /// </summary>
        public static string RoommateSearch {
            get {
                return ResourceManager.GetString("RoommateSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pokoje.
        /// </summary>
        public static string Rooms {
            get {
                return ResourceManager.GetString("Rooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liczba pokoi.
        /// </summary>
        public static string RoomsNumber {
            get {
                return ResourceManager.GetString("RoomsNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szeregowiec.
        /// </summary>
        public static string RowHouse {
            get {
                return ResourceManager.GetString("RowHouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zapisz zmiany.
        /// </summary>
        public static string SaveChanges {
            get {
                return ResourceManager.GetString("SaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zapisano zmiany.
        /// </summary>
        public static string SavedChanges {
            get {
                return ResourceManager.GetString("SavedChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zapisano filtry.
        /// </summary>
        public static string SavedFilters {
            get {
                return ResourceManager.GetString("SavedFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zapisz filtry.
        /// </summary>
        public static string SaveFilters {
            get {
                return ResourceManager.GetString("SaveFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zapisz szablon.
        /// </summary>
        public static string SaveTemplate {
            get {
                return ResourceManager.GetString("SaveTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szukaj.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyniki wyszukiwania.
        /// </summary>
        public static string SearchResult {
            get {
                return ResourceManager.GetString("SearchResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wtórny.
        /// </summary>
        public static string Secondary {
            get {
                return ResourceManager.GetString("Secondary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprzedaż.
        /// </summary>
        public static string Sell {
            get {
                return ResourceManager.GetString("Sell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyślij wiadomość.
        /// </summary>
        public static string SendMessage {
            get {
                return ResourceManager.GetString("SendMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ustawienia.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sortuj po.
        /// </summary>
        public static string SortBy {
            get {
                return ResourceManager.GetString("SortBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Powierzchnia: Największa.
        /// </summary>
        public static string Surface_Highest {
            get {
                return ResourceManager.GetString("Surface:Highest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Powierzchnia: Najmniejsza.
        /// </summary>
        public static string Surface_Lowest {
            get {
                return ResourceManager.GetString("Surface:Lowest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Powierzchnia.
        /// </summary>
        public static string SurfaceArea {
            get {
                return ResourceManager.GetString("SurfaceArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numer telefonu.
        /// </summary>
        public static string TelNumber {
            get {
                return ResourceManager.GetString("TelNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wpisz numer telefonu.
        /// </summary>
        public static string TelNumberPlaceholder {
            get {
                return ResourceManager.GetString("TelNumberPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usunięto szablon.
        /// </summary>
        public static string TemplateDeleted {
            get {
                return ResourceManager.GetString("TemplateDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szablony.
        /// </summary>
        public static string Templates {
            get {
                return ResourceManager.GetString("Templates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zapisano szablon.
        /// </summary>
        public static string TemplateSaved {
            get {
                return ResourceManager.GetString("TemplateSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kamienica.
        /// </summary>
        public static string Tenement {
            get {
                return ResourceManager.GetString("Tenement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tytuł.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodałeś zbyt dużo plików!.
        /// </summary>
        public static string TooManyFilesError {
            get {
                return ResourceManager.GetString("TooManyFilesError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odblokuj komunikację.
        /// </summary>
        public static string UnblockCommunication {
            get {
                return ResourceManager.GetString("UnblockCommunication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odobserwuj ofertę.
        /// </summary>
        public static string UnfollowOffer {
            get {
                return ResourceManager.GetString("UnfollowOffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Użytkownik z podanym adresem email już istnieje.
        /// </summary>
        public static string UserAlreadyExists {
            get {
                return ResourceManager.GetString("UserAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usunięto użytkownika.
        /// </summary>
        public static string UserDeleted {
            get {
                return ResourceManager.GetString("UserDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Należysz już do tego czatu.
        /// </summary>
        public static string UserIsAlreadyInChat {
            get {
                return ResourceManager.GetString("UserIsAlreadyInChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie znaleziono użytkownika.
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profil użytkownika.
        /// </summary>
        public static string UserProfile {
            get {
                return ResourceManager.GetString("UserProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tak.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twoje szczegóły.
        /// </summary>
        public static string YourDetails {
            get {
                return ResourceManager.GetString("YourDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twoje wiadomości.
        /// </summary>
        public static string YourMessages {
            get {
                return ResourceManager.GetString("YourMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twoje ogłoszenie wygaśnie za.
        /// </summary>
        public static string YourOfferExpiresIn {
            get {
                return ResourceManager.GetString("YourOfferExpiresIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twoje ogłoszenia.
        /// </summary>
        public static string YourOffers {
            get {
                return ResourceManager.GetString("YourOffers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twoje szablony.
        /// </summary>
        public static string YourTemplates {
            get {
                return ResourceManager.GetString("YourTemplates", resourceCulture);
            }
        }
    }
}
