//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Frost.Shared.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Errors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Errors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Frost.Shared.Resources.Errors", typeof(Errors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Powtórz hasło.
        /// </summary>
        public static string ConfirmPasswordRequiredError {
            get {
                return ResourceManager.GetString("ConfirmPasswordRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opis jest za długi. Maksymalna ilość znaków wynosi 2000..
        /// </summary>
        public static string DescriptionMaxLengthError {
            get {
                return ResourceManager.GetString("DescriptionMaxLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email jest wymagany.
        /// </summary>
        public static string EmailRequiredError {
            get {
                return ResourceManager.GetString("EmailRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email nie jest poprawny.
        /// </summary>
        public static string EmailValidError {
            get {
                return ResourceManager.GetString("EmailValidError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pole jest wymagane.
        /// </summary>
        public static string FieldRequiredError {
            get {
                return ResourceManager.GetString("FieldRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Piętro nie mieści się w zakresie..
        /// </summary>
        public static string FloorRangeError {
            get {
                return ResourceManager.GetString("FloorRangeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imię jest zbyt długie.
        /// </summary>
        public static string NameMaxLengthError {
            get {
                return ResourceManager.GetString("NameMaxLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imię jest wymagane.
        /// </summary>
        public static string NameRequiredError {
            get {
                return ResourceManager.GetString("NameRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Narodowość jest wymagana.
        /// </summary>
        public static string NationalityRequiredError {
            get {
                return ResourceManager.GetString("NationalityRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hasło jest wymagane.
        /// </summary>
        public static string PasswordRequiredError {
            get {
                return ResourceManager.GetString("PasswordRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hasła muszą pasować.
        /// </summary>
        public static string PasswordsDoNotMatchError {
            get {
                return ResourceManager.GetString("PasswordsDoNotMatchError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cena nie mieści się w zakresie..
        /// </summary>
        public static string PriceRangeError {
            get {
                return ResourceManager.GetString("PriceRangeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liczba pokoi nie mieści się w zakresie..
        /// </summary>
        public static string RoomsNumberRangeError {
            get {
                return ResourceManager.GetString("RoomsNumberRangeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Powierzchnia nie mieści się w zakresie..
        /// </summary>
        public static string SurfaceRangeError {
            get {
                return ResourceManager.GetString("SurfaceRangeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numer telefonu jest nieprawidłowy.
        /// </summary>
        public static string TelNumberIsInvalidError {
            get {
                return ResourceManager.GetString("TelNumberIsInvalidError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numer telefonu jest wymagany.
        /// </summary>
        public static string TelNumberRequiredError {
            get {
                return ResourceManager.GetString("TelNumberRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opis jest zbyt długi.
        /// </summary>
        public static string UserDescriptionTooLongError {
            get {
                return ResourceManager.GetString("UserDescriptionTooLongError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rok nie mieści się w zakresie..
        /// </summary>
        public static string YearRangeError {
            get {
                return ResourceManager.GetString("YearRangeError", resourceCulture);
            }
        }
    }
}
